### ISSUE TITLE
Unable to work on Windows 11 due to detected trojan virus

### ISSUE THREAD

**Issue by Nytra** [Gawdl3y/Resolute#48]
![Screenshot 2023-12-17 021544 edit](https://github.com/Gawdl3y/Resolute/assets/14206961/3142ee7c-4a17-43f4-8400-87526eb143ff)

Trojan:Script/Wacatac.B!ml

**Comment by Gawdl3y** [comment]
It's not a Trojan. If I were to guess, Defender sometimes identifies it as such due to the self-updating functionality. What's more frustrating is that it only sometimes screams about it, not consistently. You may just need to whitelist it.
Hopefully, as more people download it and Microsoft picks up on its existence via the usual telemetry, this problem will go away. I'm also going to submit it as a false positive on Microsoft's site, although who knows how effective that will be!

This problem will likely come and go until MS and other vendors see Tauri apps more frequently. The only permanent fix in the meantime is probably to sign the executable using an EV code signing certificate... but that costs hundreds of dollars per year to maintain, which is not an investment I can feasibly make at the moment.

See tauri-apps/tauri#2486

**Comment by Gawdl3y** [comment]
Funnily enough, it seems nothing improperly flags the MSI version of the installer with anything, according to a [VirusTotal scan](https://www.virustotal.com/gui/file/2b9b0cc98e65f54c331b4e5b371683a9c1f2ac1942cd52ad7bd4cb7e1a47eb00) - so if you'd rather not whitelist anything, you can give that a shot.

Also on the subject of VirusTotal, according to the [scan on the EXE installer](https://www.virustotal.com/gui/file/cc121d4b665fffae7a5a3848fde0342aa2d9d3a4dd5cf8154f01f9bf0a7a6923/behavior), nothing is detected in behavioural analysis. It's purely some signature-based AV that is being tripped.

**Comment by Gawdl3y** [comment]
I just released v0.4.0 and scanned both the installer and the installed EXE manually with Defender, but it didn't report anything this time around. Dunno if it's just a fluke or if it's actually okay with this version, but I didn't make any relevant changes.

**Comment by Nytra** [comment]
I tried the EXE installer for v0.4.1 and it worked. So maybe this issue can be closed? Although the problem may still crop up again in future releases.

**Comment by liny-fox** [comment]
release 0.7.1 reported with this variant:
![image](https://github.com/Gawdl3y/Resolute/assets/7400549/6cb1fdd1-f34f-4f6d-a015-9b8d65caa19a)

**Comment by XDelta** [comment]
Most recent 0.8.0 still appears to have this issue for some. According to [VirusTotal](https://www.virustotal.com/gui/file/aad09ce84b0a6e2472690cddab4bfbc3f305a87de5d1b75f5003df429650ee22?nocache=1), it is still being flagged by one vendor along with matching a yara rule on https://github.com/Gawdl3y/Resolute/blob/b3cae91233a65bf75b40ab1bf455f6057b9d7b41/crates/resolute/src/manifest.rs#L20

![aa7433c7ae](https://github.com/Gawdl3y/Resolute/assets/7883807/71e70873-872a-4e80-acd6-68e91b5641ce)
